import { Product } from './store'

export const products: Product[] = [
  {
    id: '1',
    name: 'Промышленная печь конвекционная Rational SelfCookingCenter',
    description: 'Профессиональная пароконвектомат с автоматическим управлением. Объём 20 уровней GN 1/1.',
    price: 1250000,
    image: 'https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800&h=600&fit=crop',
    category: 'Печи и пароконвектоматы',
    inStock: true,
    specifications: ['20 уровней GN 1/1', 'Автоматическое управление', 'Энергосбережение A++'],
  },
  {
    id: '2',
    name: 'Холодильный шкаф Hoshizaki под столешницу',
    description: 'Компактный холодильный шкаф для кухни. Температура от -2°C до +8°C.',
    price: 185000,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&h=600&fit=crop',
    category: 'Холодильное оборудование',
    inStock: true,
    specifications: ['Объём 200 л', 'Температура -2°C до +8°C', 'Энергокласс A+'],
  },
  {
    id: '3',
    name: 'Посудомоечная машина Winterhalter GS 502',
    description: 'Проходная посудомоечная машина для высокой производительности. 500 тарелок/час.',
    price: 890000,
    image: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&h=600&fit=crop',
    category: 'Посудомоечное оборудование',
    inStock: true,
    specifications: ['500 тарелок/час', 'Проходная', 'Экономия воды'],
  },
  {
    id: '4',
    name: 'Плита газовая профессиональная 6 конфорок',
    description: 'Профессиональная газовая плита с чугунными конфорками. Мощность 18 кВт.',
    price: 320000,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop',
    category: 'Плиты и варочные поверхности',
    inStock: true,
    specifications: ['6 конфорок', 'Мощность 18 кВт', 'Чугунные конфорки'],
  },
  {
    id: '5',
    name: 'Кухонный комбайн Robot Coupe R6',
    description: 'Профессиональный кухонный комбайн для нарезки овощей. Производительность до 300 кг/ч.',
    price: 450000,
    image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e8?w=800&h=600&fit=crop',
    category: 'Кухонные комбайны',
    inStock: true,
    specifications: ['300 кг/ч', 'Многофункциональный', 'Нержавеющая сталь'],
  },
  {
    id: '6',
    name: 'Морозильный ларь Hoshizaki 500 л',
    description: 'Горизонтальный морозильный ларь для хранения продуктов. Температура -18°C.',
    price: 220000,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&h=600&fit=crop',
    category: 'Холодильное оборудование',
    inStock: true,
    specifications: ['Объём 500 л', 'Температура -18°C', 'Энергокласс A+'],
  },
  {
    id: '7',
    name: 'Фритюрница профессиональная 2 ванны',
    description: 'Профессиональная фритюрница с двумя ваннами. Объём каждой ванны 12 л.',
    price: 180000,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop',
    category: 'Жарочное оборудование',
    inStock: true,
    specifications: ['2 ванны по 12 л', 'Автоматическая фильтрация', 'Термостат'],
  },
  {
    id: '8',
    name: 'Кофемашина профессиональная La Cimbali',
    description: 'Автоматическая кофемашина для бариста. Двухгрупповая, с панарелло.',
    price: 650000,
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&h=600&fit=crop',
    category: 'Кофейное оборудование',
    inStock: true,
    specifications: ['Двухгрупповая', 'С панарелло', 'Автоматическая'],
  },
]

export const categories = [
  'Все категории',
  'Печи и пароконвектоматы',
  'Холодильное оборудование',
  'Посудомоечное оборудование',
  'Плиты и варочные поверхности',
  'Кухонные комбайны',
  'Жарочное оборудование',
  'Кофейное оборудование',
]

